HuangWeb/HuangWeb/Models/ErrorViewModel.cs
using System;

namespace HuangWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HuangWeb/HuangWeb/Models/GetAndPostViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HuangWeb.Models
{
    public class GetAndPostViewModel
    {
        [Display(Name="输入一个0-100之间的整数")]
        //[Range(0, 100)]
        [Required]
        public int Value { get; set; }

        [Required]
        [Display(Name = "输入简要说明")]
        public string Info { get; set; }
    }
}

HuangWeb/HuangWeb/Models/ImageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;

namespace HuangWeb.Models
{
    public class ImageModel
    {
        [Required]
        public IFormFile PictureFile { get; set; }

        public string ImageUrl { get; set; }
    }
}

HuangWeb/HuangWeb/Models/TryInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HuangWeb.Models
{
    public class TryInfoViewModel
    {// this class is used to seed message from Controller to View
        public int IntValue { get; set; }
        public string StringValue { get; set; }
        public DateTime Datetime { get; set; }
    }
}

HuangWeb/HuangWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HuangWeb.Models;

namespace HuangWeb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HuangWeb/HuangWeb/Controllers/ImageUpLoadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HuangWeb.Controllers
{
    public class ImageUpLoadController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

HuangWeb/HuangWeb/Controllers/TryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HuangWeb.Models;
using Microsoft.AspNetCore.Http;

namespace HuangWeb.Controllers
{
    public class TryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// use ViewDate to pass message from Controller to View
        /// </summary>
        /// <returns></returns>
        public IActionResult UseViewData()
        {
            ViewData["刻意学习"] = "从新手到大师";
            return View();
        }

        /// <summary>
        /// use ViewBag to pass message from Controller to View
        /// </summary>
        /// <returns></returns>
        public IActionResult UseViewBag()
        {
            ViewBag.StudyMethod = "学习之道";
            return View();
        }

        /// <summary>
        /// use ViewModel to pass message from Controller to View
        /// </summary>
        /// <returns></returns>
        public IActionResult UseViewModel()
        {
            TryInfoViewModel tm = new TryInfoViewModel
            {
                IntValue = 10,
                StringValue = "ViewModel",
                Datetime = DateTime.Now
            };
            return View(tm);
        }

        /// <summary>
        /// 利用get方法的模型绑定从View向Controller中传递信息
        /// </summary>
        /// <param name="one"></param>
        /// <param name="two"></param>
        /// <returns></returns>
        public IActionResult Add(int one, int two)
        {
            ViewBag.Result = one + two;
            return View();
        }

        /// <summary>
        /// 利用post方法从View向Controller中传递信息
        /// 注意get，post的编程方式
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult GetAndPost()
        {
            return View();
        }
        [HttpPost]
        public IActionResult GetAndPost(GetAndPostViewModel model)
        {
            return View("GetAndPostResult", model);
        }

        /// <summary>
        /// use TempData to pass message from Action to Action
        /// </summary>
        /// <returns></returns>
        public IActionResult UseTempData()
        {
            return View();
        }
        [HttpPost]
        public IActionResult UseTempData(string message)
        {
            TempData["info"] = message;
            return RedirectToAction("ShowMessage");
        }
        public IActionResult ShowMessage()
        {
            if (TempData["info"] != null)
            {
                return Content(TempData["info"].ToString());
            }
            return Content("No Message!");
        }

        /// <summary>
        /// 在多次http请求中记住状态
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult UseSession()
        {
            ViewBag.Message = "please click the button";
            return View();
        }
        [HttpPost]
        public IActionResult UseSessionPostBack()
        {
            int? clickCnt = HttpContext.Session.GetInt32("ClickCount");
            if (!clickCnt.HasValue)
            {
                HttpContext.Session.SetInt32("ClickCount", 0);
                clickCnt = 0;
            }
            clickCnt++;
            HttpContext.Session.SetInt32("ClickCount", clickCnt.Value);
            ViewBag.Message = $"had clicked {clickCnt} times.";
            return View("UseSession");
        }
    }
}

HuangWeb/HuangWeb/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

HuangWeb/HuangWeb/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HuangWeb/HuangWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h2>Hello World!</h2>

HuangWeb/HuangWeb/Views/ImageUpLoad/Index.cshtml
@{ 
    ViewData["Title"] = "Image Index";
}

HuangWeb/HuangWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QiMing Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">QiMing Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Try" asp-action="Index">Try</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - QiMing Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

HuangWeb/HuangWeb/Views/Try/Add.cshtml
<h2>The answer is @ViewBag.Result</h2>

<div>@Html.ActionLink("Back", "Index")</div>

HuangWeb/HuangWeb/Views/Try/GetAndPost.cshtml
@model HuangWeb.Models.GetAndPostViewModel

<h2>Get And Post</h2>

@using (Html.BeginForm())
{

    @Html.ValidationSummary(true)

    <fieldset>
        <legend>输入相关信息</legend>
        <div>
            @Html.LabelFor(model => model.Value)
        </div>
        <div>
            @Html.EditorFor(model => model.Value)
        </div>
        <div>
            @Html.LabelFor(model => model.Info)
        </div>
        <div>
            @Html.EditorFor(model => model.Info)
        </div>

        <p>
            <br />
            <input type="submit" value="提交" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("返回", "Index")
</div>

HuangWeb/HuangWeb/Views/Try/GetAndPostResult.cshtml
@model HuangWeb.Models.GetAndPostViewModel

<h2>Post上来的数据：</h2>
<p>value=@Model.Value</p>

<p>Information=@Model.Info</p>

<div>
    @Html.ActionLink("返回", "Index")
</div>

HuangWeb/HuangWeb/Views/Try/Index.cshtml
@{ 
    ViewData["Title"] = "Try Index";
}
<h2>MVC项目中的信息传送</h2>
<hr />
<h3>Action到View</h3>
<ul>
    <li>
        @Html.ActionLink("ViewData的使用", "UseViewData")
    </li>
    <li>
        @Html.ActionLink("ViewBag的使用", "UseViewBag")
    </li>
    <li>
        @Html.ActionLink("ViewModel设计模式使用示例", "UseViewModel")
    </li>
</ul>

<hr />
<h3>“模型绑定（Model Bind）”机制示例</h3>
<ul>
    <li>
        @Html.ActionLink("使用匿名对象封装路由信息，计算1 + 2", "Add", "try", new { one = 1, two = 2 }, null)
    </li>
    <li>
        @Html.ActionLink("Get和Post配对的Action", "GetAndPost")
    </li>
</ul>

<hr />
<h3>Action到Action间的信息传送</h3>

<ul>
    <li>@Html.ActionLink("使用TempData在Action中间传送数据", "UseTempData")</li>
    <li>@Html.ActionLink("使用Session保存状态", "UseSession")</li>
</ul>

HuangWeb/HuangWeb/Views/Try/UseSession.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<form class="text-center" asp-controller="Try" asp-action="UseSessionPostBack" method="post">
    <h2>使用Session</h2>
    <button class="btn btn-default" type="submit">Click Me!</button>
    <h3 class="text-info">@ViewBag.Message</h3>
</form>

<div>
    @Html.ActionLink("返回", "Index")
</div>

HuangWeb/HuangWeb/Views/Try/UseTempData.cshtml
<h2>使用TempData在两个请求之间传送信息</h2>

@using (Html.BeginForm())
{
    <fieldset>
        <legend>要传送的信息</legend>
        <input type="text" id="message" name="message" />
        <br />
        <br />
        <input type="submit" />
    </fieldset>
}

<div>
    @Html.ActionLink("返回", "Index")
</div>

HuangWeb/HuangWeb/Views/Try/UseViewBag.cshtml
<h2>@ViewBag.StudyMethod</h2>

<div>
    @Html.ActionLink("返回", "Index")
</div>

HuangWeb/HuangWeb/Views/Try/UseViewData.cshtml
<h2><strong>刻意练习</strong>@ViewData["刻意练习"]</h2>

<div>
    @Html.ActionLink("返回", "Index")
</div>

HuangWeb/HuangWeb/Views/Try/UseViewModel.cshtml
@model HuangWeb.Models.TryInfoViewModel

<h2>收到Information对象</h2>
<p>InValue=@Model.IntValue</p>
<p>StringValue=@Model.StringValue</p>
<p>datetime=@Model.Datetime.ToString()</p>

<div>
    @Html.ActionLink("返回", "Index")
</div>